export const GOOGLE_OAUTH_CONTINUATION_GRANT_TOKEN_BYTES = 32;

export const GOOGLE_OAUTH_CONTINUATION_GRANT_RAW_TOKEN_LENGTH = 43;

export const GOOGLE_OAUTH_CONTINUATION_GRANT_DEFAULT_TTL_SECONDS = 600;

export const GOOGLE_OAUTH_CONTINUATION_GRANT_MIN_TTL_SECONDS = 120;

export const GOOGLE_OAUTH_CONTINUATION_GRANT_MAX_TTL_SECONDS = 900;
